GET http://127.0.0.1:8000/posts/
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzMjc5ODc2LCJpYXQiOjE3NDMyNzk1NzYsImp0aSI6ImYxYmI0NjIzMGYwMTQwZTU5ZWE4MDVjMzgyODEyZGY5IiwidXNlcl9pZCI6MX0.fZkD8qM_Gu_cGExFgHgCI1v8u0jWokQM92CDMblcW3o


### GET Comments
GET http://127.0.0.1:8000/comments/1/
Content-Type: application/json


### Create Post
POST http://127.0.0.1:8000/newpost/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNTE0MzYyLCJpYXQiOjE3NDM1MTQzNTIsImp0aSI6Ijc4ODIwYzUwODE4ZTQ3NjQ5YzhjMTFhMTY2OWVhOTQ5IiwidXNlcl9pZCI6NX0.YQQqcxmI4WXY3WGLTMbYolYjd4-jvlJwH7IeVQABCaU

{
    "title": "How To Make Http Request",
    "content": "You Can Make HTTP Request By Playing Basketball At Home"
}


### Login
POST http://127.0.0.1:8000/token/
Content-Type: application/json

{
    "username": "vite",
    "password": "vite"
}

### Verify Token
POST http://127.0.0.1:8000/token/verify/
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNTE0MzYyLCJpYXQiOjE3NDM1MTQzNTIsImp0aSI6Ijc4ODIwYzUwODE4ZTQ3NjQ5YzhjMTFhMTY2OWVhOTQ5IiwidXNlcl9pZCI6NX0.YQQqcxmI4WXY3WGLTMbYolYjd4-jvlJwH7IeVQABCaU"
}

### Refresh
POST http://127.0.0.1:8000/token/refresh/
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0MzU5NTkzNywiaWF0IjoxNzQzNTA5NTM3LCJqdGkiOiI5YjhhZDRmMzQ4NWI0OTBiOGUxYWQ4ZmM5ZjVjNzg5NSIsInVzZXJfaWQiOjV9.g8Vm67Xtz71iYat7q3o49SMAGAkS8lTv8rz-K-AP_To"
}

### Register
POST http://127.0.0.1:8000/register/
Content-Type: application/json

{
    "username": "moustafa",
    "email": "kareem@example.com",
    "password": "kareem"
}

### refresh token
POST http://127.0.0.1:8000/token/refresh
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0MzM0NTM1MiwiaWF0IjoxNzQzMjU4OTUyLCJqdGkiOiJkMWNhMjBlODA0Njk0NmFiYThjNjlkMjA0ZDlkMmMyNyIsInVzZXJfaWQiOjF9.cLvXfXMZbynJci0UsW7n7mjXRHB9SAf_C6Ic_2ayyBk"
}


### Toggle Like A Post
POST http://127.0.0.1:8000/upvote/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNTM1MTM4LCJpYXQiOjE3NDM1MjQzMzgsImp0aSI6ImU3Yjg5YjlhMDc2ODQyNmRiYmU1MmIwMTdjNGQ3ZWE1IiwidXNlcl9pZCI6NX0.FloBOa_dAbmpigUjT_Xq4qtbnY0dZrIATvZGV3chK54

### Get Post Comments
POST http://127.0.0.1:8000/comments/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzMjg3NTg1LCJpYXQiOjE3NDMyODM5ODUsImp0aSI6IjljZjhmZTRmOTI4ZTRjYTA4MDIyYWM5MzU1MWVjM2NlIiwidXNlcl9pZCI6MX0.QQwxrp_XCKO11ZKvMuWBoO1JgTuroZnO6BbRHuKjjxE

{
    "content": "this comment is sent from rest client"
}


### Get Questions
GET http://127.0.0.1:8000/questions/


### Get Question Details
GET http://127.0.0.1:8000/questions/2/


### Get Companies
GET http://127.0.0.1:8000/companies/


### Get Tags
GET http://127.0.0.1:8000/tags/
