# Generated by Django 5.1.7 on 2025-03-29 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_acceptencerate_question_acceptancerate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upvotes',
        ),
        migrations.AlterField(
            model_name='post',
            name='upvoters',
            field=models.ManyToManyField(blank=True, null=True, related_name='upvoted_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=7),
        ),
    ]
